# Generated by Django 3.1.7 on 2021-03-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210327_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default=1, max_length=100, verbose_name='Почта'),
            preserve_default=False,
        ),
    ]
