# Generated by Django 3.1.7 on 2021-03-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinstance',
            name='sold',
        ),
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, help_text='13 character unique number', max_length=13, unique=True),
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'In stock'), (2, 'Reserved'), (3, 'Sold')], default=1, help_text='Book status'),
        ),
    ]
