# Generated by Django 3.1.7 on 2021-03-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_remove_order_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'In stock'), (2, 'Sold')], default=1, help_text='Book status'),
        ),
    ]
