# Generated by Django 3.1.7 on 2021-03-28 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_auto_20210327_0855'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='OrderProduct',
        ),
        migrations.RenameField(
            model_name='bookinstance',
            old_name='order_item',
            new_name='order_product',
        ),
    ]
