# Generated by Django 3.1.7 on 2021-03-30 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_auto_20210328_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='order_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_order_product', to='warehouse.orderproduct'),
        ),
    ]
