# Generated by Django 3.1.7 on 2021-03-31 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_auto_20210330_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinstance',
            name='order_product',
        ),
        migrations.AddField(
            model_name='order',
            name='book',
            field=models.CharField(default=1, max_length=100, verbose_name='title'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
    ]
