# Generated by Django 3.1.7 on 2021-03-31 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_auto_20210331_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_progress', 'Заказ в обработке'), ('is_ready', 'Заказ готов'), ('completed', 'Заказ выполнен')], default='in_progress', help_text='order status', max_length=100, verbose_name='Статус заказа'),
        ),
    ]
