# Generated by Django 3.1.7 on 2021-03-31 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_auto_20210331_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_progress', 'in_progress'), ('is_ready', 'is_ready'), ('completed', 'completed')], help_text='order status', max_length=100, verbose_name='Статус заказа'),
        ),
    ]
